### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by Yahatix** [ThisNils/rust-replay-reader#3]
I have created a windows app using this parser as a base and would like to publish it. 
But for that i need to know in what ways i can use this.

**Comment by ThisNils** [comment]
Oh, well I didn't really think anyone would want to use this code 😆. As I said in the readme, it was just meant to be a small just for fun thing. But I guess I'll add an MIT license.

**Comment by Yahatix** [comment]
Thank you ☺️

**Comment by Yahatix** [comment]
I was originally using it to parse replays in the browser without the need to upload the file. Since there is a filesize limit on vercel
